server:
  port: 8761

eureka:
  client:
    register-with-eureka: false # Eureka ??? ??? ???? ??
    fetch-registry: false # ?? ???? ??(?????)? ???? ??

spring:
  application:
    name: discovery-service